spring:
    application:
        name: SocialApplication
    datasource:
        hikari:
            connection-timeout: 60000
            maximum-pool-size: 5
        url: jdbc:h2:mem:~/db_friendsnet;DB_CLOSE_DELAY=1000
        driverClassName: org.h2.Driver
        username: sa
        password: 
        
    jpa:
        hibernate:
            ddl-auto: create-drop
            show-sql: true
    logging:
        level:
            org.springframework: INFO
    server:
        port: 8080
    h2:
        console:
            enabled: true
            path: /h2-console