spring:
    application:
        name: SocialApplication
    datasource:
        hikari:
            connection-timeout: 60000
            maximum-pool-size: 5
        url: jdbc:h2:mem:~/db_friendsnet;DB_CLOSE_DELAY=1000
        driverClassName: org.h2.Driver
        username: sa
        password: 
        
    jpa:
        hibernate:
            ddl-auto: create-drop
            show-sql: true
    logging:
        level:
            org.springframework: INFO
    server:
        port: 8080
    h2:
        console:
            enabled: true
            path: /h2-console
            
    google:
        clientId: 269115313905-om54ugojq4p7huf2d1pmm2a28i8377sl.apps.googleusercontent.com
        clientSecret: ISwNVa-grZECBYz-7IpDFwEd
        accessTokenUri: https://www.googleapis.com/oauth2/v3/token
        userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
        redirectUri: http://localhost:8080/auth/google
    resource:
        userInfoUri: https://www.googleapis.com/userinfo/v2/me
        preferTokenInfo: false